import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

/**
 * Conditionally joins class names and resolves Tailwind conflicts.
 *
 * This helper is generated by shadcn/ui conventions and used by
 * `components/ui/*` via the `@/lib/utils` alias.
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
